### PR TITLE
Running Maestro-ng as a docker container

### PR DESCRIPTION
**Pull request by acaranta**
As it was suggested in #163  here is my solution in the form of a Dockerfile and a bit of help added to the Readme file.

FYI, this maestro-ng container is used in our company since well ... around a year and a half.
It work for us, therefore I thought I could share ;)

Can be tried live from : https://hub.docker.com/r/acaranta/dockmaestro/

### CODE REVIEW

**Comment by acaranta** [comment]
Corrections made according to your comments.

**Comment by mpetazzoni** [comment]
Awesome. Thanks a lot! I'm assuming you've tested it after the changes?

**Comment by acaranta** [comment]
No indeed .... :p put that on hold for the moment ... (it was  way too nice... it went too well ;) )

**Comment by acaranta** [comment]
Well OK, I should have tested ....
I just corrected the Entrypoint in the Dockerfile .... but ....
The change to alpine linux, might render the image smaller ... but it seems it breaks DNS resolution ...
I am no longer able to use this maestro docker at all with DNS names (for docker daemons access) :/
I tested simple images alpine and ubuntu ... a simple nslookup / dig works perfectly in ubuntu but not in alpine linux.
Networking/DNS seems quite weird in alpine ...

I rechecked the sizes : 
```
maestro-ng            (...)      169 MB
acaranta/dockmaestro  (...)      398.9 MB
```
and although the size is indeed doubled ... at least it works correctly ...

So I wonder ... shall I fall back to ubuntu making sure that DNS, networking will work properly (and potentially other issues I have not been able to test/see yet) and get probably way less issues in the future ?

**Comment by acaranta** [comment]
OK found the problem ... seems alpine does not use the resolv.conf like as usually ...
if you have several nameserver statements .. they are not used in the 'correct' order ... therefore it can brilliantly fail if you have like me : 
```
nameserver <internal IP1>
nameserver <internal IP2>
nameserver 8.8.8.8
```

In the current case, it searched against mainly google DNS .... which can not resolve my internal zones .... :/

Therefore, this can be an issue ... I'd say it's up to you to acknowledge if this is acceptable or not ...
It is a problem with alpine, not our implementation anyway ;)

**Comment by mpetazzoni** [comment]
Yes, there are some differences in the way the libc in Alpine Linux does DNS resolution. Here's the explanation: http://www.openwall.com/lists/musl/2015/09/15/2. That being said, your image is fine as-is for me. Would you mind squashing your commits together before I merge? Thanks!

**Comment by acaranta** [comment]
Done ;)

**Pull request merged**
